Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 60
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*
