default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: work-shifts_development

test:
  <<: *default
  database: work-shifts_test

production:
  <<: *default
  database: <%= ENV['WORK_SHIFTS_DATABASE_NAME'] %>
  username: <%= ENV['WORK_SHIFTS_DATABASE_USERNAME'] %>
  password: <%= ENV['WORK_SHIFTS_DATABASE_PASSWORD'] %>
